In [37]:
import pandas as pd
import os

from unicodedata import normalize
from collections import Counter

In [31]:
# 기존 listdir + MacOS 시스템으로 인한 (더미 파일(.DS_Store) 제거 + 한글 인식 모듈 변경) 함수
def listdir_ds_remover(dir):
    if os.path.isfile(dir+'/.DS_Store'):
        os.remove(dir+'/.DS_Store')
        list = os.listdir(dir)
        new_list=[]
        for i in list:
            i = normalize("NFC", i)
            new_list.append(i)
        return new_list
    else :
        list = os.listdir(dir)
        new_list=[]
        for i in list:
            i = normalize("NFC", i)
            new_list.append(i)
        return new_list

In [32]:
direct_list = []
hidir = listdir_ds_remover('/Users/heemin/Documents/DHLab/mv/project/저학년_landmark')
for hi in hidir:
    lowdir = listdir_ds_remover('/Users/heemin/Documents/DHLab/mv/project/저학년_landmark/'+hi)
    for low in lowdir:
        file = listdir_ds_remover('/Users/heemin/Documents/DHLab/mv/project/저학년_landmark/'+hi+'/'+low)
        for file_name in file:
            direct_list.append([f'/Users/heemin/Documents/DHLab/mv/project/저학년_landmark/{hi}/{low}/{file_name}', f'{file_name}'])

In [ ]:
for j in direct_list:
    df = pd.read_csv(j[0])
    l1 = df['total_count'].tolist()
    l2=df['emotion'].tolist()
    df1 = pd.DataFrame([l1,l2]).T
    a = list(range(l1[-1]+1))
    index_df = pd.DataFrame(a)
    df2 = pd.merge(index_df, df1, how="outer")
    df2 = df2.fillna(0)
    l3 = []
    emolist = []
    count = 0
    for i in range(len(df2)):
        if count % 25 == 0:
            if df2.iloc[i][1] != 0:
                l3.append([df2.iloc[i][0], df2.iloc[i][1]])
            else:
                try:
                    l3.append(l3[-1])
                except:
                    l3.append([0, 'none'])
        count+=1
    pd.DataFrame(l3, columns=[['count','emotion']]).to_csv('/Users/heemin/Documents/DHLab/mv/project/dir/'+j[1])

In [46]:
for j in direct_list:
    df = pd.read_csv(j[0])
    l1 = df['total_count'].tolist()
    l2 = df['emotion'].tolist()
    df1 = pd.DataFrame([l1,l2]).T
    a = list(range(l1[-1]+1))
    index_df = pd.DataFrame(a)
    df2 = pd.merge(index_df, df1, how="outer")
    df2 = df2.fillna('none')
    l3 = []
    split = 0
    for i in range(len(df2)):
        if i % 25 == 0 or i == len(df2):
            emolist = df2[1][split:i].to_list()
            emocount = Counter(emolist)
            top3 = emocount.most_common(n=3)
            if len(top3) == 0:
                l3.append([i, 'Neutral'])
            else:
                if top3[0][0] == 'none': 
                    if len(top3) == 1:
                        l3.append([i, 'Neutral'])
                    else:
                        l3.append([i, top3[1][0]])
                elif top3[0][0] == 'Neutral':
                    if len(top3) == 1:
                        l3.append([i, top3[0][0]])
                    elif top3[0][1] < 13:
                        if top3[1][0] == 'none':
                            if len(top3) == 2:
                                l3.append([i, 'Neutral'])
                            else:
                                l3.append([i, top3[2][0]])
                        else:
                            l3.append([i, top3[1][0]])
                    else:
                        if top3[1][0] == 'none':
                            if len(top3) == 2:
                                l3.append([i, 'Neutral'])
                            else:
                                l3.append([i, top3[0][0]])
                        else:
                            l3.append([i, top3[0][0]])
                else:
                    l3.append([i, top3[0][0]])
                split+=25

    pd.DataFrame(l3, columns=[['count','emotion']]).to_csv('/Users/heemin/Documents/DHLab/mv/project/dir/emotion_top3/'+j[1])

In [ ]:
# 1-1 {'1':'KSY', '2':'PSG'}
# 2-1 {}

In [139]:
import pandas as pd
df = pd.read_csv('/home/heemin/mv/dir/voice_sentiment/session1_metaverse1.csv', index_col=0)
df['total_count'] = df['second']*25
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68 entries, 0 to 67
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Person       68 non-null     int64
 1   Time         68 non-null     object
 2   Speech       68 non-null     object
 3   sentiment    68 non-null     object
 4   second       68 non-null     int64
 5   total_count  68 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.7+ KB

In [140]:
ksy = df['Person'] == 1
psg = df['Person'] == 2

In [141]:
df[ksy]

    Person   Time               Speech sentiment  second  total_count
0        1  00:06               만들어 좋지  positive       6          150
6        1  01:00     진짜 이거 진짜 이거 힌트 네   neutral      60         1500
14       1  02:04  우리가 더 올라온 거 아니야 이 정   neutral     124         3100
23       1  02:45         자꾸 튕기는 것 같은데  negative     165         4125
27       1  03:02       아니 아니 거 아니가 아닌   neutral     182         4550
35       1  04:03  안 돼 안 돼 안 돼 안 돼 안 돼   neutral     243         6075
37       1  04:11          안 돼 안 돼 안 돼   neutral     251         6275
53       1  05:47              할 수 있을까   neutral     347         8675
56       1  05:59   맞았어 맞았어 맞았어 맞았어 았았  positive     359         8975
57       1  06:03       어디 어디 어디 어디 어디   neutral     363         9075
66       1  07:09              아니야 이거는   neutral     429        10725

In [142]:
df[psg]

,Person,Time,Speech,sentiment,second,total_count
1,2,00:07,그래 열심히 막고,negative,7,175
2,2,00:14,빨리 망아 누구라도,negative,14,350
4,2,00:39,그걸 나왔네,neutral,39,975
7,2,01:04,다 다리 모자 엄청 들어요. 파이팅 이와 노아 파이팅 아니야 아니 아니야 잘 있다.,negative,64,1600
9,2,01:27,에 들어가 있었어 진짜 골기한 거야 일단 있어야지 그리고 너는 왜 여기에,negative,87,2175
12,2,01:48,야 빨리 하자 이들아 빨리 이 이제 너한테 패스 할게 안돼 어떻게 하는지 모른다 면서,negative,108,2700
18,2,02:23,너 아빠 키들 빨리 먹자,neutral,143,3575
22,2,02:41,이 벽이 닫기만 하면 다,neutral,161,4025
29,2,03:17,저요,neutral,197,4925
31,2,03:19,저 뛰어다니는 회사 누구야 다,neutral,199,4975
33,2,03:45,야 넌 복수할 거야 이제 음악 지금 5 대 2야 3년 남았어 어떻게 하면 될까 완전,negative,225,5625
39,2,04:23,빨리 막아버리마,negative,263,6575
43,2,04:40,역시나,neutral,280,7000
48,2,05:09,빨리 이겨야 돼 이제 열심히 해야 돼 또 챙길 수 있는 이 오늘,neutral,309,7725
50,2,05:18,힘들어 우리는 빨간 팀이다. 전설의 레이드 빨간팀,negative,318,7950
52,2,05:30,우리 전설 같아 잘해보자,positive,330,8250
58,2,06:05,우리 이미 팀워크 잔인했다. 여기 이 올라와 있죠.,negative,365,9125
61,2,06:35,이번 재밌겠는데 이번에야 말로,neutral,395,9875
63,2,06:49,그건이야말로 엄청 개미 있는 싸움이 되겠어,negative,409,10225
64,2,06:57,널 밟아 죽이겠다.,negative,417,10425
67,2,07:21,이게 이제 끝났어요.,neutral,441,11025

In [144]:
k1 = df[ksy]
l1 = k1['total_count'].tolist()
l2 = k1['sentiment'].tolist()
df1 = pd.DataFrame([l1,l2]).T
df1[0] = df1[0].astype('int')
a = list(range(l1[-1]+1))
index_df = pd.DataFrame(a)
df2 = pd.merge(index_df, df1, how="outer")
df2 = df2.fillna('none')
l3 = []
split = 0
for i in range(len(df2)):
    if i % 25 == 0 or i == len(df2):
        emolist = df2[1][split:i].to_list()
        emocount = Counter(emolist)
        top3 = emocount.most_common(n=3)
        if len(top3) == 0:
            l3.append([i, 'none'])
        else:
            if top3[0][0] == 'none': 
                if len(top3) == 1:
                    l3.append([i, 'none'])
                else:
                    l3.append([i, top3[1][0]])
            elif top3[0][0] == 'Neutral':
                if len(top3) == 1:
                    l3.append([i, top3[0][0]])
                elif top3[0][1] < 13:
                    if top3[1][0] == 'none':
                        if len(top3) == 2:
                            l3.append([i, 'Neutral'])
                        else:
                            l3.append([i, top3[2][0]])
                    else:
                        l3.append([i, top3[1][0]])
                else:
                    if top3[1][0] == 'none':
                        if len(top3) == 2:
                            l3.append([i, 'Neutral'])
                        else:
                            l3.append([i, top3[0][0]])
                    else:
                        l3.append([i, top3[0][0]])
            else:
                l3.append([i, top3[0][0]])
            split += 25
pd.DataFrame(l3, columns=[['total_count','emotion']]).to_csv('/home/heemin/mv/dir/voice_sentiment_name/'+'KSY.csv')

In [145]:
psgdf = pd.read_csv('/home/heemin/mv/dir/voice_sentiment_name/PSG.csv', index_col=0)
ksydf = pd.read_csv('/home/heemin/mv/dir/voice_sentiment_name/KSY.csv', index_col=0)

In [164]:
psgdf.columns=['total_count', 'PSG_voice']
ksydf.columns=['total_count', 'KSY_voice']

In [165]:
m1 = pd.read_csv('/home/heemin/mv/dir/frame_emotion.csv',index_col=0)

In [166]:
m1T = m1.T[:-2]
col = m1.T[-2:-1].T['id'].tolist()[1:]
col.insert(0, 'total_count')
m1T.columns = col
m1T['total_count'] = m1T['total_count'].astype('int')

In [167]:
m2 = pd.merge(m1T, psgdf,how='left', on='total_count')
m3 = pd.merge(m2, ksydf,how='left', on='total_count')
m3 = m3.fillna('none')

In [168]:
m3

     total_count      LYG      HJY      LJH      KSY PSG_voice KSY_voice
0             25  Neutral    Happy     Fear     Fear      none      none
1             50  Neutral    Happy      Sad      Sad      none      none
2             75  Neutral    Happy  Neutral  Neutral      none      none
3            100  Neutral    Happy  Neutral  Neutral      none      none
4            125  Neutral    Happy    Happy    Happy      none      none
..           ...      ...      ...      ...      ...       ...       ...
438        10975      Sad  Neutral  Neutral  Neutral      none      none
439        11000  Neutral  Neutral  Neutral  Neutral      none      none
440        11025  Neutral  Neutral  Neutral  Neutral      none      none
441        11050  Neutral  Neutral  Neutral  Neutral      none      none
442        11075  Neutral      Sad     Fear     Fear      none      none

[443 rows x 7 columns]

In [170]:
m3.T.to_csv('/home/heemin/mv/dir/frame_emotion_voice.csv')